[package]
name = "cards_with_vrf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
merlin = "3.0.0"
schnorrkel = "0.10.2"
rand_core = "0.6.3"
rand = "0.8.5"
