[package]
name = "iterators"
version = "0.1.0"
authors = ["Tomasz Waszczyk <tomasz@waszczyk.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
